### ISSUE TITLE
nzpy fails to clean up database connection, tests faill

### ISSUE THREAD

**Issue by shabbir10july** [IBM/nzpy#22]
Raising this on behalf of @mderoy

I have a test runner which uses the python unittest framework. before each test, I ensure the test database is deleted by implementing the setUp function

  ```
 def setUp(self):
        if self.connection is None:
            logging.getLogger().addHandler(logging.NullHandler())
            self.connection = nzpy.connect(user="admin", unix_sock='/tmp/.s.PGSQL.5480', database="system")
            try:
                with self.connection.cursor() as cursor:
                    cursor.execute("DROP DATABASE GROOMCATTEST")
            except:
                pass

```
however, if my tests connects to the database that I'm creating, my tests start to fail (note you'll need to alter this test since I'm testing catalog changes....simply connecting to the second database, and having tearDown or setUp remove the database should repro the issue)

```
    def test_alterdatabase_setbackupset(self):
        with self.connection.cursor() as cursor:
            cursor.execute("CREATE DATABASE GROOMCATTEST")
            cursor.execute("SELECT AUTOGROOMBACKUPSET FROM _T_DATABASE WHERE DATNAME = 'GROOMCATTEST'")
            self.assertEqual(cursor.fetchone()[0], 'epoch')            cursor.execute("ALTER DATABASE GROOMCATTEST AUTOGROOM BACKUPSET '20201022181337'")
            cursor.execute("SELECT AUTOGROOMBACKUPSET FROM _T_DATABASE WHERE DATNAME = 'GROOMCATTEST'")
            self.assertEqual(cursor.fetchone()[0], '2020-10-22 14:13:37')        gcconn = nzpy.connect(user="admin", unix_sock='/tmp/.s.PGSQL.5480', database="GROOMCATTEST")
        with gcconn.cursor() as cursor:
             cursor.execute("ALTER DATABASE GROOMCATTEST AUTOGROOM BACKUPSET '20201022181337'")
             cursor.execute("SELECT AUTOGROOMBACKUPSET FROM _V_DATABASE WHERE DATNAME = 'GROOMCATTEST'")
             self.assertEqual(cursor.fetchone()[0], 20201022181337)
        gcconn.close()
```

It would seem like my new connection does not disconnect from the database before my setUp function runs as would be expected, causing my drop database to fail with
`nzpy.core.ProgrammingError: ERROR: DROP DATABASE: could not acquire lock for "GROOMCATTEST"`
which then causes my next test to fail because CREATE DATABASE fails (the database already exists)
nzpy needs to ensure that the database connection is disconnected as soon as the object goes out of scope, and implement the explicit close() function

**Comment by mderoy** [comment]
hmmm theres some weirdness here....myconnection.close() seems to work in some cases I've tried outside the test runner....

**Comment by shabbir10july** [comment]
This issue is fixed with the fix for issue https://github.com/IBM/nzpy/issues/33. Hence closing this issue.
