### ISSUE TITLE
Constant defined twice

### ISSUE THREAD

**Issue by joebeeson** [IBM/nzpy#28]
The constant `RESPONSE_SEVERITY` is defined twice with different values. 

https://github.com/IBM/nzpy/blob/ca02b16d03ea80c4184035deaa7193cc0e4d50be/nzpy/core.py#L1022-L1023

I'd submit a PR to resolve but wanted to confirm which value it _should_ retain going forward.

**Comment by shabbir10july** [comment]
@joebeeson: This part of code is derived from postgres python driver.  We are not using these error code so it is safe to remove this part of code.
